### ISSUE TITLE
htoprc is not being loaded/saved

### ISSUE THREAD

**Issue by agkphysics** [maxiberta/htop-snap#14]
When you run `htop` and change the settings using F2 and quit, the settings are not saved, so that subsequent uses of `htop` have default settings.

When I run using the full path:
```
/snap/htop/current/usr/local/bin/htop
```
the settings are correctly loaded from `~/.config/htop/htoprc`. So I suspect this has something to do with the wrapper script mentioned in #2.

This is using the `htop 3.0.5` snap.

**Comment by maxiberta** [comment]
> When you run htop and change the settings using F2 and quit, the settings are not saved, so that subsequent uses of htop have default settings.

The snap uses `~/snap/htop/current/.config/htop/htoprc` for settings. Does that path exist in your home directory? Is there anything out of the ordinary that might prevent htop from accessing it? What linux distro are you running, and what snapd version? It works as expected as far as I can tell (on Ubuntu). Please run `snap version`, and check logs for related messages.

> When I run using the full path
> ...
> the settings are correctly loaded from ~/.config/htop/htoprc

This bypasses all the confinement and other snapd features, running binary outside of snapd's control. That's why it attempts to read config directly from that default location. When running as a snap instead, the home directory is set to `~/snap/htop/current` and the config file location is relative to that path.

o/

**Comment by maxiberta** [comment]
To check exactly what the snap can see, you can run a shell inside the snap's environment:

```sh
$ snap run --shell htop
$ ls ~/.config/htop/htoprc  # this runs inside the snap environment
```

**Comment by agkphysics** [comment]
@maxiberta I've copied the file to `~/snap/htop/current/.config/htop/htoprc` and verified that `htop` can access it within the snap environment, but it still doesn't load or change the settings.

There doesn't seem to be anything particularly wrong with my setup that should cause it to fail. However, `journalctl` contains some interesting info regarding apparmor:
```
Jun 02 16:42:39 sc401081 systemd[1885]: Started snap.htop.htop.74b1b90e-a39a-4c88-8840-6f1ed6eb65e6.scope.
Jun 02 16:42:39 sc401081 kernel: audit: type=1400 audit(1622608959.250:61773): apparmor="DENIED" operation="open" profile="snap.htop.htop" name="/home/me/.config/htop/htoprc" pid=1049511 comm="htop" requested_mask="r" denied_mask="r" fsuid=2430749 ouid=2430749
Jun 02 16:42:39 sc401081 audit[1049511]: AVC apparmor="DENIED" operation="open" profile="snap.htop.htop" name="/home/me/.config/htop/htoprc" pid=1049511 comm="htop" requested_mask="r" denied_mask="r" fsuid=2430749 ouid=2430749
Jun 02 16:42:47 sc401081 audit[1049511]: AVC apparmor="DENIED" operation="open" profile="snap.htop.htop" name="/home/me/.config/htop/htoprc" pid=1049511 comm="htop" requested_mask="wc" denied_mask="wc" fsuid=2430749 ouid=2430749
Jun 02 16:42:47 sc401081 kernel: audit: type=1400 audit(1622608967.118:61774): apparmor="DENIED" operation="open" profile="snap.htop.htop" name="/home/me/.config/htop/htoprc" pid=1049511 comm="htop" requested_mask="wc" denied_mask="wc" fsuid=2430749 ouid=2430749
Jun 02 16:42:47 sc401081 systemd[1885]: snap.htop.htop.74b1b90e-a39a-4c88-8840-6f1ed6eb65e6.scope: Succeeded.
```
It seems `htop` is trying to access the config file in my home directory instead of the snap-specific folder and is being denied read/write access.

Version info:
- Ubuntu 20.04.2 LTS
```
$ snap version
snap    2.50.1
snapd   2.50.1
series  16
ubuntu  20.04
kernel  5.8.0-53-generic
```

**Comment by maxiberta** [comment]
Afaict, config file location can be [overridden via env var `HTOPRC`](https://manpages.ubuntu.com/manpages/impish/en/man1/htop.1.html#config%20file), and config file directory [via `XDG_CONFIG_HOME`](https://github.com/htop-dev/htop/blob/master/Settings.c#L415); but they are not usually set. Can you please check if any of those is set in the snap environment? Also just in case, $HOME should point to `$HOME/snap/htop/current`. Something like this:
```bash
$ snap run --shell htop -c env | grep -w 'HOME\|HTOPRC\|XDG_CONFIG_HOME'
```
For example, I can reproduce the apparmor denials with these:
```bash
$ env XDG_CONFIG_HOME=$HOME/.config htop
Can not save configuration to /home/me/.config/htop/htoprc: Permission denied

$ env HTOPRC=$HOME/.config/htop/htoprc htop
Can not save configuration to /home/me/.config/htop/htoprc: Permission denied
```

**Comment by agkphysics** [comment]
@maxiberta `XDG_CONFIG_HOME` was set in my `.bashrc`, although I can't remember exactly why I put it there. Removing it solved the problem and now `htop` can read/write the snap-specific `htoprc`.
