### ISSUE TITLE
Incompatible htop license change

### ISSUE THREAD

**Issue by BenBE** [maxiberta/htop-snap#15]
Hi @maxiberta - you've listed this github repository as MIT licensed and it performs a build of the htop sources. The htop sources are made available under the GPLv2 license, which is incompatible with the MIT license. Derivative works based on GPLv2 licensed works are again subject to being licensed under the GPLv2. Could you update the license on this repository accordingly please?

References: https://en.wikipedia.org/wiki/GNU_General_Public_License#Compatibility_and_multi-licensing

Many thanks!

-- BenBE (on behalf of the htop maintainers)

**Comment by maxiberta** [comment]
Hey! I am not a lawyer, but I believe this MIT license applies only to this repository's contents, which is basically just a `snapcraft.yaml` file. The resulting snap builds are already marked as GPLv2 in the Snap Store. See [the web page listing](https://snapcraft.io/htop) and `snap info htop | grep license`. Is that ok for you? Let me know o/

**Comment by maxiberta** [comment]
Also, the snap binaries include `license: GPL-2.0` in their internal metadata as per the [snapcraft.yaml](https://github.com/maxiberta/htop-snap/blob/master/snap/snapcraft.yaml#L21) file. Just install the snap and check `/snap/htop/current/meta/snap.yaml`.

**Comment by BenBE** [comment]
Thank you very much for your quick reply.

The MIT licensing for the snap packaging is - of course - okay, but a casual visitor to the repository may get confused by the two applicable rules for the different parts. We'd thus suggest to include some more obvious wording to the README to make this distinction between your build files (under MIT) and the upstream sources (GPLv2) more obvious.

On the topic of being more explicit, there's also the `htop.png` which is a scaled copy of the upstream logo and AFAICT is lacking proper attribution. Please mention the origin of that file, as it deviates in licensing from the overall license of the repository.

NB: The logo of htop has slightly changed about a year ago. Would be nice if it could be updated.

If you like I can create a PR with the desired changes.

**Comment by maxiberta** [comment]
> If you like I can create a PR with the desired changes.

Yes, please, go ahead. Thanks!
