### ISSUE TITLE
log spam AVC apparmor="DENIED"

### ISSUE THREAD

**Issue by katian** [maxiberta/htop-snap#19]
Hello,

how to avoid log spam ?

`AVC apparmor="DENIED" operation="open" profile="snap.htop.htop" name="/proc/2599/task/2600/" pid=11974 comm="htop" requested_mask="r" denied_mask="r" fsuid=1000 ouid=1000`

i remove snap and choose apt version :face_exhaling:

**Comment by maxiberta** [comment]
I can't reproduce this issue with current htop 3.2.2 and all interfaces connected. If you're still experiencing this issue, please share details to help reproduce, such as htop version, the output of `snap version` and any other relevant bits. Thanks.

**Comment by katian** [comment]
$ sudo apt remove htop
$ snap install htop

Apparently I don't have this spam problem anymore.

```
$ snap version 
snap    2.58.2
snapd   2.58.2
series  16
ubuntu  22.04
kernel  5.19.0-32-generic
```
