### ISSUE TITLE
ENV lost when executing htop

### ISSUE THREAD

**Issue by pachulo** [maxiberta/htop-snap#2]
I think that something is wrong with the ENV when executing htop, because, for example, when I choose the "Tree" view, the "lines" are drawn using ASCII:
![image](https://user-images.githubusercontent.com/3256953/40581357-aff81960-6156-11e8-9890-5264f75dbc04.png)

But if I execute the binary directly, like this:

`$ /snap/htop/current/bin/htop`

UTF-8 characters are used:

![image](https://user-images.githubusercontent.com/3256953/40581371-132e5a80-6157-11e8-9b68-aaad07b7bb44.png)

**Comment by maxiberta** [comment]
Hi! Thanks for the report. The environment is _not_ lost when running the snap, as shown by `snap run --shell htop -c env`. But what's missing seems to be the _precompiled_ locale definitions for all locales, except the default `C`, `C.UTF-8` and `POSIX` (as shown by `snap run --shell htop -c "locale -a"`).

I've (hopefully) fixed it by bundling all base _text_ locales with the `htop` snap, and adding a small wrapper script that generates the binary locale on the first run if needed (from the `LANG` envvar), and caches it in `$SNAP_USER_COMMON/locale` (i.e. `$HOME/snap/htop/common/locale`). This is now published in the `candidate` channel, waiting for feedback before promoting to stable. Please let me know if it works for you :-)

Thanks again!

**Comment by pachulo** [comment]
Wow, that was fast!
I was wrong then: tested it and it works OK now, thanks a lot!!!

**Comment by maxiberta** [comment]
The updated snap is now published on the `stable` channel.
