### ISSUE TITLE
Htop is dead, long live htop-dev

### ISSUE THREAD

**Issue by sparkiegeek** [maxiberta/htop-snap#8]
The htop project is being maintained by @htop-dev - https://github.com/htop-dev/htop could the snap be moved to this one and reflect the [3.0.0 release](https://github.com/htop-dev/htop/blob/3.0.0/ChangeLog)?

**Comment by maxiberta** [comment]
Hey! Sure. I [planned to do the switch](https://github.com/hishamhm/htop/issues/992#issuecomment-675481704) 2 weeks ago, but then I thought it might be a bit too premature (and was busy with other stuff). Now that the original developer chimed in and gave his blessing to the fork, legitimising it, I'll do it asap.
Thanks!

**Comment by maxiberta** [comment]
Edge and candidate builds now point to the new upstream (`master` branch, and `3.0.0` tag respectively). Also switched the base to `core20`, btw. Will promote the snaps in candidate to stable in a couple of days if no issues are reported.

**Comment by maxiberta** [comment]
Version `3.0.1` is now available on `stable`.
