### ISSUE TITLE
htop won't work with kitty

### ISSUE THREAD

**Issue by konomikitten** [maxiberta/htop-snap#9]
Kitty is currently not available as a snap so I cannot install it with snap. Kitty via apt and htop via apt work fine but Kitty via apt and htop via snap does not.

```
ubuntu@ubuntu-inspiron:~$ snap install htop
htop 3.0.2 from Maximiliano Bertacchini (maxiberta) installed
ubuntu@ubuntu-inspiron:~$ apt list kitty
Listing... Done
kitty/focal,now 0.15.0-1build1 amd64 [installed]
ubuntu@ubuntu-inspiron:~$ snap list htop
Name  Version  Rev   Tracking       Publisher  Notes
htop  3.0.2    1332  latest/stable  maxiberta  -
ubuntu@ubuntu-inspiron:~$ htop
locales-launch: Data of en_AU locale not found, generating, please wait...
Error opening terminal: xterm-kitty.
ubuntu@ubuntu-inspiron:~$
```

**Comment by maxiberta** [comment]
Thanks for your feedback! Please try the latest build on `edge` which I believe fixes the issue as per https://github.com/maxiberta/htop-snap/commit/a158b778e0e0c62a70e7693b4c3004081556e1fc. o/

**Comment by konomikitten** [comment]
Hopefully someone else can test this as I don't have this installation installed any more. Sorry.

**Comment by maxiberta** [comment]
It works for me. This is now fixed on the `stable` channel.
Please reopen if you find any related issues.
Thanks!
